// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiqlxudrjerawlbndkyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpcWx4dWRyamVyYXdsYm5ka3lqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNjQ4NzQsImV4cCI6MjA1NTg0MDg3NH0.LEdLz4bQ6mYlC-nrs44_VEBuULHfG3eLlihtMKCc1-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);