// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxslpdrzvkvaeveohpbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4c2xwZHJ6dmt2YWV2ZW9ocGJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjcyNjUsImV4cCI6MjA3MzUwMzI2NX0.DpbXV6Lbg1e_5OjByPOCO8B_ccI9UsU0-dQ8BcGI_Zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});